### ISSUE TITLE
Failed to install due to "sharp" module. 

### ISSUE THREAD

**Issue by javaarchive** [danielroehrig/vinutes#43]
![installerror](https://user-images.githubusercontent.com/20248577/103724360-f9cc6280-4f88-11eb-8923-292ad6ab004b.PNG)
Using the latest MSI I got through all of the dialogs until this happended.

**Comment by danielroehrig** [comment]
Sorry, somehow I wasn't notified about this. Sharp has the tendency to ruin my day. Unfortunately, I'm a Linux user and need to start a windows machine to track down this bug. Could you tell me, what OS you are using?

**Comment by danielroehrig** [comment]
@javaarchive  I could replicate the bug.  Then I built a new version on my local machine (Windows 10) and it worked. So, hopefully, the next release should fix this issue.

**Comment by danielroehrig** [comment]
@javaarchive version 0.3.1 which will be released tonight will fix this issue. If not, please contact me.
